# Generated by Django 4.2.4 on 2024-05-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('adpassword', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
