# Generated by Django 4.2.4 on 2024-06-04 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sporthub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facname', models.TextField(max_length=30)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.TextField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('datestart', models.DateField()),
                ('quantity', models.IntegerField()),
                ('bookid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sporthub.student')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sporthub.facility')),
            ],
        ),
    ]
